In [ ]:
import numpy as np
import pandas as pd

In [1]:
df = pd.read_excel("AI_CHIR_DIG_adjusted.xlsx", sheet_name="Second cleanup")

NameError: name 'pd' is not defined

In [ ]:
df.head()

AGE_SURGERY  SEX  ASA  TOBACCO  PHX_PULM  PHX_DM    BMI Hb_PREOP  \
0           61  2.0  2.0      2.0         1       1  16.23        3   
1           70  1.0  2.0      1.0         1       2  27.68        4   
2           39  1.0  1.0      2.0         2       1  20.23        4   
3           38  1.0  2.0      2.0         2       1  20.30        3   
4           25  2.0  2.0      1.0         1       1  17.30        3   

   PHX_ABDOMINAL_SURGERY  PHX_CVD  ...  Unnamed: 28  Unnamed: 29  Unnamed: 30  \
0                    2.0        2  ...          NaN          NaN          NaN   
1                    1.0        2  ...          NaN          NaN          NaN   
2                    1.0        2  ...          NaN          NaN          NaN   
3                    1.0        1  ...          NaN          NaN          NaN   
4                    2.0        1  ...          NaN          NaN          NaN   

   TACHYCARDIA_J1  WBC_J1  CRP_J2  INVASION_PERINEURAL  INVASION_VASC  \
0             1.0     1.0       -                  2.0            1.0   
1             1.0     1.0       2                  2.0            1.0   
2             1.0     1.0       2                  1.0            1.0   
3             1.0     1.0       1                  2.0            2.0   
4             1.0     1.0       1                  1.0            1.0   

   INVASION_LYMPH REINTERVENTION  
0             1.0            1.0  
1             1.0            1.0  
2             1.0            1.0  
3             1.0            1.0  
4             1.0            1.0  

[5 rows x 38 columns]

In [ ]:
columns_to_drop = ['Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30']
df_cleaned = df.drop(columns=columns_to_drop)

print(df_cleaned)

     AGE_SURGERY  SEX  ASA  TOBACCO  PHX_PULM  PHX_DM    BMI Hb_PREOP  \
0             61  2.0  2.0      2.0         1       1  16.23        3   
1             70  1.0  2.0      1.0         1       2  27.68        4   
2             39  1.0  1.0      2.0         2       1  20.23        4   
3             38  1.0  2.0      2.0         2       1  20.30        3   
4             25  2.0  2.0      1.0         1       1  17.30        3   
..           ...  ...  ...      ...       ...     ...    ...      ...   
223           73  1.0  2.0      1.0         1       2    NaN        2   
224           55  1.0  2.0      2.0         2       1  25.73        3   
225           58  1.0  2.0      2.0         2       2  21.60        4   
226           82  1.0  NaN      2.0         2       2    NaN        3   
227           62  2.0  2.0      2.0         2       1  28.52        5   

     PHX_ABDOMINAL_SURGERY  PHX_CVD  ...  RESECTION_ADJ.ORGAN.T4  CONVERSION  \
0                      2.0        2  ...   

In [ ]:
columns_to_extract = ['SEX', 'ASA', 'TOBACCO', 'PHX_PULM', 'PHX_DM', 'SURGERY_DURATION']
df_extract = df[columns_to_extract]

print(df_extract)

     SEX  ASA  TOBACCO  PHX_PULM  PHX_DM SURGERY_DURATION
0    2.0  2.0      2.0         1       1                3
1    1.0  2.0      1.0         1       2                3
2    1.0  1.0      2.0         2       1                3
3    1.0  2.0      2.0         2       1                3
4    2.0  2.0      1.0         1       1                3
..   ...  ...      ...       ...     ...              ...
223  1.0  2.0      1.0         1       2              NaN
224  1.0  2.0      2.0         2       1                2
225  1.0  2.0      2.0         2       2                2
226  1.0  NaN      2.0         2       2              NaN
227  2.0  2.0      2.0         2       1                2

[228 rows x 6 columns]


In [ ]:
df_cleaned = df_extract.replace('-', np.nan).dropna().reset_index(drop=True)
df_cleaned = df_cleaned.dropna().reset_index(drop=True)

df_cleaned['SEX'] = df_cleaned['SEX'].astype(int)
df_cleaned['ASA'] = df_cleaned['ASA'].astype(int)
df_cleaned['TOBACCO'] = df_cleaned['TOBACCO'].astype(int)
df_cleaned['PHX_PULM'] = df_cleaned['PHX_PULM'].astype(int)
df_cleaned['PHX_DM'] = df_cleaned['PHX_DM'].astype(int)
df_cleaned['SURGERY_DURATION'] = df_cleaned['SURGERY_DURATION'].astype(int)

print(df_cleaned)

     SEX  ASA  TOBACCO  PHX_PULM  PHX_DM  SURGERY_DURATION
0      2    2        2         1       1                 3
1      1    2        1         1       2                 3
2      1    1        2         2       1                 3
3      1    2        2         2       1                 3
4      2    2        1         1       1                 3
..   ...  ...      ...       ...     ...               ...
181    1    2        1         1       1                 2
182    1    2        1         2       2                 2
183    1    2        2         2       1                 2
184    1    2        2         2       2                 2
185    2    2        2         2       1                 2

[186 rows x 6 columns]


In [ ]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SEX               186 non-null    int64
 1   ASA               186 non-null    int64
 2   TOBACCO           186 non-null    int64
 3   PHX_PULM          186 non-null    int64
 4   PHX_DM            186 non-null    int64
 5   SURGERY_DURATION  186 non-null    int64
dtypes: int64(6)
memory usage: 8.8 KB


# Train

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X = df_cleaned[['SEX', 'TOBACCO', 'PHX_PULM', 'PHX_DM', 'ASA']]
y = df_cleaned['SURGERY_DURATION']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred = model.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")

Accuracy: 0.42


In [ ]:
y_pred

array([3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 1, 2, 3, 2, 3, 3, 2, 3, 3, 3, 3, 2,
       3, 2, 3, 2, 2, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3])

In [ ]:
y_true = y_test

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision (macro):", precision_score(y_test, y_pred, average='macro'))
print("Recall (macro):", recall_score(y_test, y_pred, average='macro'))
print("F1 Score (macro):", f1_score(y_test, y_pred, average='macro'))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.42105263157894735
Precision (macro): 0.2062937062937063
Recall (macro): 0.23897058823529413
F1 Score (macro): 0.2136089577950043
Confusion Matrix:
 [[ 0  2  1  0]
 [ 0  4 12  0]
 [ 1  4 12  0]
 [ 0  1  1  0]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

print("MSE:", mean_squared_error(y_true, y_pred))
print("MAE:", mean_absolute_error(y_true, y_pred))
print("R2 Score:", r2_score(y_true, y_pred))

MSE: 0.8157894736842105
MAE: 0.6578947368421053
R2 Score: -0.5918918918918921
